# 02_train_models.py
# BIAT Risk Monitor - Train and compare ML models
#
# Input:
#   dataset_ml_clean.csv generated by 01_prepare_dataset.py
#
# Usage:
#   python 02_train_models.py --input dataset_ml_clean.csv --output-dir ml_outputs
#
# Fast test on smaller sample:
#   python 02_train_models.py --input dataset_ml_clean.csv --output-dir ml_outputs --sample 200000
#
# Outputs:
#   ml_outputs/model_metrics.csv
#   ml_outputs/predictions_test.csv
#   ml_outputs/clients_risque_top.csv
#   ml_outputs/best_model.pkl

import argparse
from pathlib import Path
import warnings

warnings.filterwarnings("ignore")

import joblib
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.base import clone


def get_lightgbm_model():
    """
    Use LightGBM if installed. If not installed, use HistGradientBoosting as a fallback.
    To install LightGBM:
        pip install lightgbm
    """
    try:
        from lightgbm import LGBMClassifier

        return (
            "LightGBM",
            LGBMClassifier(
                n_estimators=350,
                learning_rate=0.05,
                max_depth=-1,
                num_leaves=64,
                subsample=0.85,
                colsample_bytree=0.85,
                class_weight="balanced",
                random_state=42,
                n_jobs=-1,
            ),
        )
    except Exception:
        return (
            "HistGradientBoosting_Fallback",
            HistGradientBoostingClassifier(
                learning_rate=0.06,
                max_iter=250,
                max_leaf_nodes=64,
                random_state=42,
            ),
        )


def build_preprocessor(X: pd.DataFrame) -> ColumnTransformer:
    categorical_features = X.select_dtypes(include=["object", "string", "category"]).columns.tolist()
    numeric_features = [c for c in X.columns if c not in categorical_features]

    numeric_pipeline = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ]
    )

    categorical_pipeline = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", min_frequency=50)),
        ]
    )

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_pipeline, numeric_features),
            ("cat", categorical_pipeline, categorical_features),
        ],
        remainder="drop",
    )

    return preprocessor


def get_models():
    lightgbm_name, lightgbm_model = get_lightgbm_model()

    models = {
        "LogisticRegression": LogisticRegression(
            max_iter=1000,
            class_weight="balanced",
            solver="lbfgs",
            n_jobs=-1,
            random_state=42,
        ),
        "RandomForest": RandomForestClassifier(
            n_estimators=120,
            max_depth=14,
            min_samples_leaf=30,
            class_weight="balanced_subsample",
            random_state=42,
            n_jobs=-1,
        ),
        lightgbm_name: lightgbm_model,
        "MLP_DeepLearning": MLPClassifier(
            hidden_layer_sizes=(64, 32),
            activation="relu",
            solver="adam",
            alpha=0.0005,
            learning_rate_init=0.001,
            max_iter=60,
            early_stopping=True,
            validation_fraction=0.15,
            random_state=42,
        ),
    }

    return models


def predict_scores(model, X_test):
    """
    Return probability-like risk scores.

    Important correction for BIAT Risk Monitor:
    the model may output values extremely close to 1.0. Technically this means
    "very high confidence", but in a banking dashboard it should not be shown
    as an absolute 100% certainty. We therefore cap the operational score at 0.95.
    """
    if hasattr(model, "predict_proba"):
        scores = model.predict_proba(X_test)[:, 1]
    elif hasattr(model, "decision_function"):
        raw_scores = model.decision_function(X_test)
        scores = 1 / (1 + np.exp(-raw_scores))
    else:
        scores = model.predict(X_test)

    return np.clip(scores, 0.0, 0.95)


def evaluate_model(model_name: str, model, X_test, y_test, threshold: float) -> dict:
    y_score = predict_scores(model, X_test)
    y_pred = (y_score >= threshold).astype(int)

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

    metrics = {
        "model": model_name,
        "threshold": threshold,
        "roc_auc": roc_auc_score(y_test, y_score),
        "recall": recall_score(y_test, y_pred, zero_division=0),
        "precision": precision_score(y_test, y_pred, zero_division=0),
        "f1_score": f1_score(y_test, y_pred, zero_division=0),
        "accuracy": accuracy_score(y_test, y_pred),
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp),
    }

    return metrics


def evaluate_overfitting(model_name: str, model, X_train, y_train, X_test, y_test) -> dict:
    """Compare train AUC and test AUC to detect real overfitting."""
    train_scores = predict_scores(model, X_train)
    test_scores = predict_scores(model, X_test)

    train_auc = roc_auc_score(y_train, train_scores)
    test_auc = roc_auc_score(y_test, test_scores)
    gap = train_auc - test_auc

    if gap < 0.03:
        verdict = "No overfitting"
    elif gap < 0.07:
        verdict = "Slight overfitting"
    else:
        verdict = "Overfitting risk"

    return {
        "model": model_name,
        "train_auc": round(float(train_auc), 4),
        "test_auc": round(float(test_auc), 4),
        "auc_gap": round(float(gap), 4),
        "verdict": verdict,
    }


def evaluate_early_detection(model_name: str, model, X_test, y_test, test_df, threshold: float) -> dict | None:
    """
    Evaluate the model only on clients that look safe in the current month.
    This is important for the jury because it shows whether the model can detect
    future risk before the current indicators are already critical.
    """
    required = {"NBRJDEP", "RISK_BRUT"}
    if not required.issubset(set(test_df.columns)):
        return None

    mask = (
        (pd.to_numeric(test_df["NBRJDEP"], errors="coerce").fillna(0).values == 0)
        & (pd.to_numeric(test_df["RISK_BRUT"], errors="coerce").fillna(0).values == 0)
    )

    if int(mask.sum()) < 100:
        return None

    X_clean = X_test[mask]
    y_clean = y_test.values[mask]

    if len(set(y_clean)) < 2:
        return None

    y_score = predict_scores(model, X_clean)
    y_pred = (y_score >= threshold).astype(int)

    return {
        "model": model_name,
        "early_detection_auc": round(float(roc_auc_score(y_clean, y_score)), 4),
        "early_detection_recall": round(float(recall_score(y_clean, y_pred, zero_division=0)), 4),
        "early_detection_samples": int(mask.sum()),
    }


def choose_feature_columns(df: pd.DataFrame) -> list[str]:
    excluded_columns = {
        "TARGET_RISK_30J",
        "NEXT_PERIODE",
        "NEXT_NBRJDEP",
        "NEXT_RISK_BRUT",
        "CPTE",
        "CODE_CLIENT",
    }

    # PERIODE is excluded from direct modeling to avoid date memorization.
    # The time split already uses PERIODE.
    excluded_columns.add("PERIODE")

    feature_columns = [c for c in df.columns if c not in excluded_columns]
    return feature_columns


def stratified_sample(df: pd.DataFrame, sample_size: int | None) -> pd.DataFrame:
    if sample_size is None or sample_size <= 0 or sample_size >= len(df):
        return df

    print(f"Sampling {sample_size:,} rows for faster training...")
    _, sampled = train_test_split(
        df,
        test_size=sample_size,
        stratify=df["TARGET_RISK_30J"],
        random_state=42,
    )
    return sampled.sort_values("PERIODE").reset_index(drop=True)


def main():
    parser = argparse.ArgumentParser(description="Train BIAT Risk Monitor ML models.")
    parser.add_argument("--input", default="dataset_ml_clean.csv", help="Clean dataset path.")
    parser.add_argument("--output-dir", default="ml_outputs", help="Directory for outputs.")
    parser.add_argument("--threshold", type=float, default=0.70, help="Risk threshold for classification.")
    parser.add_argument(
        "--sample",
        type=int,
        default=0,
        help="Optional stratified sample size for faster training. Use 0 for full dataset.",
    )

    args = parser.parse_args()

    input_path = Path(args.input)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    print(f"[1/7] Loading clean dataset: {input_path}")
    df = pd.read_csv(input_path, low_memory=False)
    df["PERIODE"] = pd.to_datetime(df["PERIODE"], errors="coerce")
    df = df.dropna(subset=["PERIODE", "TARGET_RISK_30J"])

    print(f"      Shape: {df.shape}")
    print(f"      Target distribution:")
    print(df["TARGET_RISK_30J"].value_counts(normalize=True).round(4))
    print(df["TARGET_RISK_30J"].value_counts())

    if args.sample and args.sample > 0:
        df = stratified_sample(df, args.sample)
        print(f"      Sampled shape: {df.shape}")

    print("[2/7] Time-based train/test split")
    # Professional choice: train on older periods, test on newest periods.
    unique_periods = sorted(df["PERIODE"].dropna().unique())
    split_index = int(len(unique_periods) * 0.80)
    split_period = unique_periods[split_index]

    train_df = df[df["PERIODE"] < split_period].copy()
    test_df = df[df["PERIODE"] >= split_period].copy()

    print(f"      Split period: {pd.to_datetime(split_period).date()}")
    print(f"      Train shape: {train_df.shape}")
    print(f"      Test shape: {test_df.shape}")

    feature_columns = choose_feature_columns(df)
    X_train = train_df[feature_columns]
    y_train = train_df["TARGET_RISK_30J"].astype(int)

    X_test = test_df[feature_columns]
    y_test = test_df["TARGET_RISK_30J"].astype(int)

    print("[3/7] Building preprocessing pipeline")
    preprocessor = build_preprocessor(X_train)

    print("[4/7] Training models")
    models = get_models()
    metrics_list = []
    overfit_list = []
    early_list = []
    fitted_models = {}

    for model_name, estimator in models.items():
        print(f"\n--- Training {model_name} ---")

        pipeline = Pipeline(
            steps=[
                ("preprocessor", clone(preprocessor)),
                ("model", estimator),
            ]
        )

        pipeline.fit(X_train, y_train)
        metrics = evaluate_model(model_name, pipeline, X_test, y_test, args.threshold)
        metrics_list.append(metrics)
        fitted_models[model_name] = pipeline

        print(
            f"ROC-AUC={metrics['roc_auc']:.4f} | "
            f"Recall={metrics['recall']:.4f} | "
            f"Precision={metrics['precision']:.4f} | "
            f"F1={metrics['f1_score']:.4f} | "
            f"Accuracy={metrics['accuracy']:.4f}"
        )
        print(
            f"Confusion Matrix: TN={metrics['tn']} FP={metrics['fp']} "
            f"FN={metrics['fn']} TP={metrics['tp']}"
        )

        overfit = evaluate_overfitting(model_name, pipeline, X_train, y_train, X_test, y_test)
        overfit_list.append(overfit)
        print(
            f"Overfit check: Train AUC={overfit['train_auc']:.4f} | "
            f"Test AUC={overfit['test_auc']:.4f} | Gap={overfit['auc_gap']:.4f} | "
            f"{overfit['verdict']}"
        )

        early = evaluate_early_detection(model_name, pipeline, X_test, y_test, test_df, args.threshold)
        if early is not None:
            early_list.append(early)
            print(
                f"Early Detection: AUC={early['early_detection_auc']:.4f} | "
                f"Recall={early['early_detection_recall']:.4f} | "
                f"Samples={early['early_detection_samples']:,}"
            )

    print("\n[5/7] Saving metrics")
    metrics_df = pd.DataFrame(metrics_list).sort_values(
        by=["f1_score", "roc_auc", "recall"],
        ascending=False,
    )
    metrics_path = output_dir / "model_metrics.csv"
    metrics_df.to_csv(metrics_path, index=False, encoding="utf-8")
    print(metrics_df)

    overfit_path = output_dir / "overfitting_report.csv"
    pd.DataFrame(overfit_list).to_csv(overfit_path, index=False, encoding="utf-8")

    early_path = output_dir / "early_detection_metrics.csv"
    if early_list:
        pd.DataFrame(early_list).to_csv(early_path, index=False, encoding="utf-8")

    best_model_name = metrics_df.iloc[0]["model"]
    best_model = fitted_models[best_model_name]

    print(f"\nBest model selected: {best_model_name}")

    print("[6/7] Saving predictions and top risky clients")
    y_score = predict_scores(best_model, X_test)
    y_pred = (y_score >= args.threshold).astype(int)

    predictions = test_df[["PERIODE", "CPTE", "CODE_CLIENT", "TARGET_RISK_30J"]].copy()
    predictions["RISK_SCORE"] = y_score
    predictions["RISK_SCORE_PERCENT"] = np.round(y_score * 100, 1)
    predictions["PREDICTED_RISK"] = y_pred

    # Add useful context columns if available
    for col in ["NBRJDEP", "RISK_BRUT", "NET_MONTHLY_IN", "SECTOR", "INDUSTRY", "EMPLOYMENT_STATUS"]:
        if col in test_df.columns:
            predictions[col] = test_df[col].values

    predictions_path = output_dir / "predictions_test.csv"
    predictions.to_csv(predictions_path, index=False, encoding="utf-8")

    top_clients = predictions.sort_values("RISK_SCORE", ascending=False).head(500)
    top_clients_path = output_dir / "clients_risque_top.csv"
    top_clients.to_csv(top_clients_path, index=False, encoding="utf-8")

    print(f"      Saved: {predictions_path}")
    print(f"      Saved: {top_clients_path}")

    print("[7/7] Saving best model")
    model_path = output_dir / "best_model.pkl"
    joblib.dump(
        {
            "model_name": best_model_name,
            "threshold": args.threshold,
            "feature_columns": feature_columns,
            "pipeline": best_model,
            "metrics": metrics_df.to_dict(orient="records"),
        },
        model_path,
    )

    print(f"      Saved: {model_path}")

    print("\n✅ Training completed")
    print("Main outputs:")
    print(f"  - {metrics_path}")
    print(f"  - {predictions_path}")
    print(f"  - {top_clients_path}")
    print(f"  - {model_path}")
    print(f"  - {overfit_path}")
    if early_list:
        print(f"  - {early_path}")


if __name__ == "__main__":
    main()
